// Generates src/version.ts from package.json — the single source of truth.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const out = `// Generated by scripts/gen-version.mjs from package.json — do not edit.\nexport const SDK_VERSION = '${version}';\n`;
writeFileSync(join(root, 'src', 'version.ts'), out);
